### ISSUE TITLE
Pre-Release suggestion for major version change

### ISSUE THREAD

**Issue by seanwessmith** [mskelton/vscode-npm-outdated#21]
whats the error
its suggesting a change from ^1.4.5-lts.1 to ^2.0.0-rc.4

whats expected
it only suggests changes within the 1.X.X range

how to reproduce. 
install multer ^1.4.5-lts.1. the vscode-npm-outdated extension will incorrectly suggest upgrade to ^2.0.0-rc.4 pre-release

<img width="681" alt="Screenshot 2023-04-10 at 10 49 43 AM" src="https://user-images.githubusercontent.com/8315103/230939382-ed6cc52d-3150-4833-b05e-afb5aa09e372.png">

**Comment by rentalhost** [comment]
Oh yes... The versioning system that is used is "semver", and any [**word**](https://semver.org/lang/pt-BR/#spec-item-12) used is considered a prerelease version (eg. alpha, beta, dev). In this case, as this package uses the word "lts" (although it is evidently not a prerelease word, but a LTS release), every word is considered as prerelease. So basically the suggestion is to upgrade to a more advanced prerelease.

Ideally, the maintainer of the "multer" package would use the semver pattern, and avoid using the word "lts" for this purpose. Otherwise, the other solution would be for this plugin to add the most common prerelease words (thousands though) or exclude non-standard words like "lts".

As a last solution, we could add a setting for the user to determine which words should be ignored as prerelease word, or even disable the prerelease suggestion feature entirely, but I still think it's overkill.

**Comment by rentalhost** [comment]
ref https://github.com/expressjs/multer/issues/1155

**Comment by seanwessmith** [comment]
thanks for the quick reply, wish I asked sooner. I've been manually dealing with this for months!
I switched to multers semver version 1.4.4 and everythings good now
